apiVersion: v1
kind: Service
metadata:
  name: test-create-service-3-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: test-create-service-3
